let
  inherit (builtins) attrValues concatLists foldl' map;

  # Users
  users = {
    czichy = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKQgoSENg960XY9wU77q8p1+4WgUhEb10xlc27RWcmNE czichy@desktop"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKKAL9mtLn2ASGNkOsS38GXrLDNmLLedb0XNJzhOxtAB christian@czichy.com"
    ];
  };
  # A key for recovery purpose, generated by `ssh-keygen -t ed25519 -a 256 -C "ryan@agenix-recovery"` with a strong passphrase
  # and keeped it offline in a safe place.
  recovery_key = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOOIWIyyiKt60nCN3WvFudmP2ju0iaE7PYSoWZj1xu+f czichy@agenix-recovery"];

  # Hosts
  machines = {
    HL-1-MRZ-HOST-01 = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIELTffOa/Vh2x/CxDqKJXnwfji/aHLYbbG3ewwjFMHxZ czichy@HL-1-MRZ-HOST-01"];
    HL-1-MRZ-HOST-02 = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDPR8KYYsWTQ+sOFMlKXTJU6ZDG84ebHtqI4wotvCYzH"];
    HL-1-MRZ-HOST-03 = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE1mhPCuc7o7lNp1FWaByYr0snO2rnwd9gH8WabEeybt"];
    #    HL-1-OZ-PC-01 = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKfYUpuZeYCkKCNL22+jUBroV4gaZYJOjcRVPDZDVXSp root@desktop"];
    HL-1-OZ-PC-01 = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKgzh2Ic2KC2n2Au3Nr8mj0nJ1GRZ0jkcMpccUEVPncg"];
  };

  # Shorthand aliases for various collections of host keys
  servers = concatLists (map (host: machines.${host}) ["HL-1-MRZ-SBC-01"]);
  workstations = concatLists (map (host: machines.${host}) ["HL-1-OZ-PC-01"]);

  all = foldl' (a: b: concatLists [a b]) [users.czichy] (attrValues machines);
in {
  inherit (users) czichy;
  inherit recovery_key;
  inherit
    (machines)
    HL-1-MRZ-HOST-01
    HL-1-MRZ-HOST-02
    HL-1-MRZ-HOST-03
    HL-1-OZ-PC-01
    ;
  inherit servers workstations all;

  # Additional utilities
  mkGlobal = list: concatLists [list users.czichy];
  common = {};
  hosts = {
    HL-1-OZ-PC-01 = {
      users = {
        root = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
        czichy = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
      };
    };

    HL-1-MRZ-HOST-02 = {
      users = {
        root = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
        czichy = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
      };
    };

    HL-1-MRZ-HOST-01 = {
      users = {
        root = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
        czichy = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
      };
    };

    HL-1-MRZ-HOST-03 = {
      users = {
        root = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
        czichy = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
      };
    };

    HL-4-PAZ-PROXY-01 = {
      users = {
        root = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
        czichy = {
          sshKey = null;
          authorizedKeys = users.czichy;
        };
      };
    };
  };
}
