{
  localFlake,
  inputs,
  secretsPath,
}: {
  config,
  lib,
  system,
  hostName,
  pkgs,
  ...
}:
with builtins;
with lib; let
  inherit
    (localFlake.lib)
    isModuleLoadedAndEnabled
    mkImpermanenceEnableOption
    mkAgenixEnableOption
    mkOverrideAtHmModuleLevel
    ;

  cfg = config.tensorfiles.hm.programs.ib-tws;
  _ = mkOverrideAtHmModuleLevel;

  impermanenceCheck =
    (isModuleLoadedAndEnabled config "tensorfiles.hm.system.impermanence") && cfg.impermanence.enable;
  impermanence =
    if impermanenceCheck
    then config.tensorfiles.hm.system.impermanence
    else {};

  agenixCheck =
    (isModuleLoadedAndEnabled config "tensorfiles.hm.security.agenix") && cfg.agenix.enable;

  # ---------------------------------------------------------------------------
  # Config file generators
  # ---------------------------------------------------------------------------

  boolStr = b:
    if b
    then "true"
    else "false";

  # Generate jts.ini content from an instance config
  mkJtsIni = instCfg: let
    s = instCfg.settings;
    g = instCfg.gateway;
    tradingMode =
      if instCfg.mode == "live"
      then "l"
      else "p";
    gatewaySection = optionalString (instCfg.app == "gateway") ''
      [IBGateway]
      WriteDebug=false
      TrustedIPs=${concatStringsSep "," g.trustedIPs}
      ApiOnly=${boolStr g.apiOnly}
      LocalServerPort=${toString g.localServerPort}
      RemoteHostOrderRouting=ndc1.ibllc.com
      RemotePortOrderRouting=4001

    '';
  in
    gatewaySection
    + ''
      [Logon]
      useRemoteSettings=${boolStr s.useRemoteSettings}
      TimeZone=${s.timeZone}
      Individual=1
      FontSize=${toString s.fontSize}
      tradingMode=${tradingMode}
      colorPalletName=${s.colorPalette}
      Locale=${s.locale}
      os_titlebar=${boolStr s.osTitlebar}
      UseSSL=true
      s3store=true
      screenHeight=${toString s.screenHeight}
      ibkrBranding=${s.ibkrBranding}

      [Communication]
      Region=${s.region}
    '';

  # Generate tws.vmoptions content from an instance config
  mkVmOptions = instCfg: let
    jvm = instCfg.jvm;
  in ''
    #
    # Generated by NixOS – manual edits below '### keep on update' are preserved by TWS.
    # Re-seed by deleting this file and running 'home-manager switch'.
    #

    # maximum Java heap size
    -Xmx${toString jvm.maxHeapMb}m

    # GC settings
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=200
    -XX:ParallelGCThreads=20
    -XX:ConcGCThreads=5
    -XX:InitiatingHeapOccupancyPercent=70

    -Dinstaller.uuid=59323349-e28a-41ad-8203-3b3798beba86
    -DvmOptionsPath=$VMOPTIONS
    -Dsun.awt.nopixfmt=true
    -Dsun.java2d.noddraw=true
    -Dswing.boldMetal=false
    -Dsun.locale.formatasdefault=true

    ### keep on update
    ${concatStringsSep "\n" jvm.extraOptions}
  '';

  # Config dir name matches the ib-start convention
  instanceConfigDir = instCfg: ".ib-${instCfg.app}-${instCfg.mode}-${instCfg.channel}";

  # ---------------------------------------------------------------------------
  # Wrapper script
  # ---------------------------------------------------------------------------

  ib-start = pkgs.writeShellScriptBin "ib-start" ''
    set -euo pipefail

    # Defaults
    APP="tws"
    MODE="paper"
    CHANNEL="stable"

    usage() {
      echo "Usage: ib-start [--app tws|gateway] [--mode live|paper] [--channel stable|latest]"
      echo ""
      echo "Starts IB TWS or Gateway with credentials from agenix secrets."
      echo ""
      echo "Options:"
      echo "  --app       tws or gateway (default: tws)"
      echo "  --mode      live or paper (default: paper)"
      echo "  --channel   stable or latest (default: stable)"
      echo "  --help      Show this help"
      exit 0
    }

    while [[ $# -gt 0 ]]; do
      case "$1" in
        --app) APP="$2"; shift 2 ;;
        --mode) MODE="$2"; shift 2 ;;
        --channel) CHANNEL="$2"; shift 2 ;;
        --help|-h) usage ;;
        *) echo "Unknown option: $1"; usage ;;
      esac
    done

    # Read credentials from agenix secrets (defined in credentials.nix)
    # Find the latest agenix generation dynamically (generation number changes on each rebuild)
    AGENIX_BASE="''${XDG_RUNTIME_DIR}/agenix.d"
    AGENIX_GEN="$(ls -1 "$AGENIX_BASE" 2>/dev/null | sort -n | tail -1)"
    if [[ -z "$AGENIX_GEN" ]]; then
      echo "Warning: No agenix generation found in $AGENIX_BASE"
    fi
    AGENIX_DIR="$AGENIX_BASE/$AGENIX_GEN"
    if [[ "$MODE" == "paper" ]]; then
      USER_SECRET="$AGENIX_DIR/ibkr_paper_user"
      PASS_SECRET="$AGENIX_DIR/ibkr_paper_password"
    else
      USER_SECRET="$AGENIX_DIR/ibkr_user"
      PASS_SECRET="$AGENIX_DIR/ibkr_password"
    fi

    if [[ -f "$USER_SECRET" && -f "$PASS_SECRET" ]]; then
      export IBKR_USER="$(cat "$USER_SECRET")"
      export IBKR_PASSWORD="$(cat "$PASS_SECRET")"
    else
      echo "Warning: Credentials not found, starting without auto-login."
      echo "  Expected: $USER_SECRET and $PASS_SECRET"
    fi

    # Set per-constellation config directory to keep settings separate
    export IBKR_CONFIG_DIR="$HOME/.ib-''${APP}-''${MODE}-''${CHANNEL}"
    mkdir -p "$IBKR_CONFIG_DIR"

    # Export trading mode so tws-wrap.sh can pass tradingMode= to TWS
    export IBKR_MODE="$MODE"

    # Select the right binary
    if [[ "$CHANNEL" == "latest" ]]; then
      if [[ "$APP" == "gateway" ]]; then
        echo "Error: Gateway is not available in the latest channel. Use --channel stable instead."
        exit 1
      fi
      BIN="ib-tws-latest"
    else
      if [[ "$APP" == "gateway" ]]; then
        BIN="ib-gw"
      else
        BIN="ib-tws-native"
      fi
    fi

    echo "Starting IB $APP ($CHANNEL) in $MODE mode..."
    echo "Config dir: $IBKR_CONFIG_DIR"
    exec "$BIN" "$@"
  '';

  # ---------------------------------------------------------------------------
  # Desktop entries
  # ---------------------------------------------------------------------------

  mkDesktopEntry = name: app: mode: channel: icon:
    pkgs.makeDesktopItem {
      inherit name;
      desktopName = "IB ${
        if app == "tws"
        then "TWS"
        else "Gateway"
      } ${
        if channel == "stable"
        then "Stable"
        else "Latest"
      } ${
        if mode == "live"
        then "Live"
        else "Paper"
      }";
      exec = "${ib-start}/bin/ib-start --app ${app} --mode ${mode} --channel ${channel}";
      icon = icon;
      categories = ["Office" "Finance"];
      comment = "Interactive Brokers ${
        if app == "tws"
        then "Trader Workstation"
        else "Gateway"
      } (${channel}, ${mode})";
    };

  # Generate desktop entries from instances (deduplicated by app/mode/channel)
  instanceDesktopEntries =
    mapAttrsToList (name: instCfg:
      mkDesktopEntry
      "ib-${instCfg.app}-${instCfg.mode}-${instCfg.channel}"
      instCfg.app
      instCfg.mode
      instCfg.channel
      "ib-tws-native")
    cfg.instances;
in {
  options.tensorfiles.hm.programs.ib-tws = with types; {
    enable = mkEnableOption ''
      Interactive Brokers TWS and Gateway with auto-login via agenix secrets.
    '';
    impermanence = {
      enable = mkImpermanenceEnableOption;
    };
    agenix = {
      enable = mkAgenixEnableOption;
    };

    # -------------------------------------------------------------------------
    # Per-instance configuration
    # -------------------------------------------------------------------------
    instances = mkOption {
      description = ''
        Per-instance TWS/Gateway configuration.
        Each entry seeds a <literal>jts.ini</literal> and <literal>tws.vmoptions</literal>
        in <literal>~/.ib-&lt;app&gt;-&lt;mode&gt;-&lt;channel&gt;/</literal> on first
        activation. Delete those files and run <literal>home-manager switch</literal>
        to re-seed with updated Nix values.
      '';
      default = {};
      example = literalExpression ''
        {
          tws-paper-stable = {
            app     = "tws";
            mode    = "paper";
            channel = "stable";
            settings.timeZone    = "Europe/Berlin";
            settings.fontSize    = 21;
            settings.colorPalette = "dark";
          };
          gw-paper-stable = {
            app     = "gateway";
            mode    = "paper";
            channel = "stable";
            gateway.localServerPort = 4002;
            gateway.trustedIPs      = [ "127.0.0.1" "10.15.0.0/16" ];
          };
        }
      '';
      type = attrsOf (submodule {
        options = {
          app = mkOption {
            type = enum ["tws" "gateway"];
            default = "tws";
            description = "TWS or IB Gateway.";
          };
          mode = mkOption {
            type = enum ["paper" "live"];
            default = "paper";
            description = "Paper or live trading mode.";
          };
          channel = mkOption {
            type = enum ["stable" "latest"];
            default = "stable";
            description = "TWS release channel. Gateway is only available on stable.";
          };

          # jts.ini – [Logon] / [Communication]
          settings = {
            timeZone = mkOption {
              type = str;
              default = "Europe/Berlin";
              description = "Java timezone string for the TWS clock.";
            };
            fontSize = mkOption {
              type = int;
              default = 21;
              description = "UI font size in points.";
            };
            locale = mkOption {
              type = enum ["en" "de" "fr" "es" "it" "ja" "zh"];
              default = "en";
              description = "TWS UI locale.";
            };
            colorPalette = mkOption {
              type = enum ["dark" "light"];
              default = "dark";
              description = "TWS color theme.";
            };
            osTitlebar = mkOption {
              type = bool;
              default = false;
              description = "Use the OS window titlebar instead of the TWS custom one.";
            };
            ibkrBranding = mkOption {
              type = enum ["pro" "lite"];
              default = "pro";
              description = "IBKR Pro or Lite branding.";
            };
            screenHeight = mkOption {
              type = int;
              default = 2160;
              description = "Screen height in pixels (used by TWS for scaling).";
            };
            useRemoteSettings = mkOption {
              type = bool;
              default = false;
              description = "Sync settings via IBKR cloud (requires login).";
            };
            region = mkOption {
              type = enum ["usr" "us" "eu" "hk"];
              default = "usr";
              description = "Communication region / routing.";
            };
          };

          # jts.ini – [IBGateway] (only used when app = \"gateway\")
          gateway = {
            apiOnly = mkOption {
              type = bool;
              default = true;
              description = "Run in API-only mode (no GUI order entry).";
            };
            localServerPort = mkOption {
              type = int;
              default = 4000;
              description = "Local API port the Gateway listens on.";
            };
            trustedIPs = mkOption {
              type = listOf str;
              default = ["127.0.0.1"];
              description = "Comma-separated list of trusted API client IPs.";
            };
          };

          # tws.vmoptions
          jvm = {
            maxHeapMb = mkOption {
              type = int;
              default = 2048;
              description = "Maximum Java heap size in MiB (-Xmx).";
            };
            extraOptions = mkOption {
              type = listOf str;
              default = [];
              description = "Additional JVM flags appended after '### keep on update'.";
              example = ["-Dawt.useSystemAAFontSettings=gasp"];
            };
          };
        };
      });
    };
  };

  config = mkIf cfg.enable (mkMerge [
    # |----------------------------------------------------------------------| #
    {
      home.packages =
        [
          inputs.self.packages.${system}.ib-tws-native
          inputs.self.packages.${system}.ib-tws-native-latest
          ib-start
        ]
        # Desktop entries derived from configured instances
        ++ instanceDesktopEntries
        # Fallback entries for unconfigured combos (backwards compat)
        ++ optionals (cfg.instances == {}) [
          (mkDesktopEntry "ib-tws-stable-paper" "tws" "paper" "stable" "ib-tws-native")
          (mkDesktopEntry "ib-tws-stable-live" "tws" "live" "stable" "ib-tws-native")
          (mkDesktopEntry "ib-tws-latest-paper" "tws" "paper" "latest" "ib-tws-native")
          (mkDesktopEntry "ib-tws-latest-live" "tws" "live" "latest" "ib-tws-native")
          (mkDesktopEntry "ib-gw-stable-paper" "gateway" "paper" "stable" "ib-tws-native")
          (mkDesktopEntry "ib-gw-stable-live" "gateway" "live" "stable" "ib-tws-native")
        ];
    }
    # |----------------------------------------------------------------------| #
    # Seed jts.ini + tws.vmoptions for each declared instance
    # |----------------------------------------------------------------------| #
    (mkIf (cfg.instances != {}) {
      home.activation = mapAttrs' (name: instCfg: let
        configDir = instanceConfigDir instCfg;
        jtsIniFile = pkgs.writeText "ib-${name}-jts.ini" (mkJtsIni instCfg);
        vmOptsFile = pkgs.writeText "ib-${name}-tws.vmoptions" (mkVmOptions instCfg);
      in
        nameValuePair "ib-tws-seed-${name}" (hm.dag.entryAfter ["writeBoundary"] ''
          _ibConfigDir="$HOME/${configDir}"
          $DRY_RUN_CMD mkdir -p "$_ibConfigDir"

          if [[ ! -f "$_ibConfigDir/jts.ini" ]]; then
            $DRY_RUN_CMD cp "${jtsIniFile}" "$_ibConfigDir/jts.ini"
            $DRY_RUN_CMD chmod 644 "$_ibConfigDir/jts.ini"
            echo "ib-tws: seeded $HOME/${configDir}/jts.ini"
          fi

          if [[ ! -f "$_ibConfigDir/tws.vmoptions" ]]; then
            $DRY_RUN_CMD cp "${vmOptsFile}" "$_ibConfigDir/tws.vmoptions"
            $DRY_RUN_CMD chmod 644 "$_ibConfigDir/tws.vmoptions"
            echo "ib-tws: seeded $HOME/${configDir}/tws.vmoptions"
          fi
        ''))
      cfg.instances;
    })
    # |----------------------------------------------------------------------| #
    # Credentials are defined in credentials.nix, no duplicate secrets needed here
    # |----------------------------------------------------------------------| #
    (mkIf impermanenceCheck {
      home.persistence."${impermanence.persistentRoot}" = {
        directories =
          # Legacy config dirs (direct invocation without ib-start)
          [
            ".ib-tws-native"
            ".tws-latest"
            ".ib-gw"
          ]
          # Per-instance dirs derived from declared instances
          ++ mapAttrsToList (_name: instCfg: instanceConfigDir instCfg) cfg.instances;
      };
    })
    # |----------------------------------------------------------------------| #
  ]);

  meta.maintainers = with localFlake.lib.maintainers; [czichy];
}
